minimumReleaseAge: 10080


allowBuilds:
  - esbuild
  - core-js

strictDepBuilds: true

blockExoticSubdeps: true
engineStrict: true
lockfileVersion: 3
autoInstallPeers: true
strictPeerDependencies: false
preferOffline: true
